const actionTypes = {
  GET_DRAGONS: 'GET_DRAGONS',
  DRAGONS_RECEIVED: 'DRAGONS_RECEIVED',
  ADD_DRAGON: 'ADD_DRAGON',
  DRAGON_ADDED: 'DRAGON_ADDED',
  EDIT_DRAGON: 'EDIT_DRAGON',
  DRAGON_EDITED: 'DRAGON_EDITED',
  DELETE_DRAGON: 'DELETE_DRAGON',
  DRAGON_DELETED: 'DRAGON_DELETED'
};

export default actionTypes;
