const actionTypes = {
  ADD_USER: 'ADD_USER',
  USER_ADDED: 'USER_ADDED',
  ADD_USER_FAILED: 'ADD_USER_FAILED',
  GET_DRAGONS: 'GET_DRAGONS',
  DRAGONS_RECEIVED: 'DRAGONS_RECEIVED',
  GET_DRAGONS_FAILED: 'GET_DRAGONS_FAILED',
  ADD_DRAGON: 'ADD_DRAGON',
  DRAGON_ADDED: 'DRAGON_ADDED',
  ADD_DRAGON_FAILED: 'ADD_DRAGON_FAILED',
  EDIT_DRAGON: 'EDIT_DRAGON',
  DRAGON_EDITED: 'DRAGON_EDITED',
  EDIT_DRAGON_FAILED: 'EDIT_DRAGON_FAILED',
  DELETE_DRAGON: 'DELETE_DRAGON',
  DRAGON_DELETED: 'DRAGON_DELETED',
  DELETE_DRAGON_FAILED: 'DELETE_DRAGON_FAILED'
};

export default actionTypes;
